{% set version = "1.8.3" %}

package:
  name: cloud_sptheme
  version: {{ version }}

source:
  fn: cloud_sptheme-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cloud_sptheme/cloud_sptheme-{{ version }}.tar.gz
  sha256: 60f03e89117bd8271d97321176d48001b9a640f611f54f22ad1d23824e335413

build:
  number: 0
  preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - sphinx >=1.4

test:
  imports:
    - cloud_sptheme
    - cloud_sptheme.ext

about:
  home: https://bitbucket.org/ecollins/cloud_sptheme
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A nice sphinx theme named 'Cloud', and some related extensions.

extra:
  recipe-maintainers:
    - jakirkham
