travis:
  secure:
    BINSTAR_TOKEN: TrMqJg1FMSfnt7GArOFRjOLHkMOAZeTQkYH4oHbAjnzf/ONm7jX+M77xqhMQ4Lc/NEoOarJokMYdlQx06NsmPJhfAndY8ReJ7dHpriq6bDZYmkCmU4GoXoMJvXC7aNAibtBR7Mjm7TvXol2PNSHUQuaTG5IgujG8+XGCRsuhJK2/it7hsgZhC10P+ZrORMuhy590xqtX4iY4qslarmcy7EhAVd5Sou9aXM+dD350UiQY4u1Dgc0GkP+gm5/rHq1IM1/3mMAyFYwLejJPvPZAXrG62hXxOoQIxE+f5/XE0fw8r1RwVLVgRs7ET75mNlQfH80rTo0bDsOdZvyf9MFIb/Bhxfae5sgG7wR7Snig0yTDGEWrpcCrmTKBwg1KXlDNAdrk4imseJu53OelKg6fLxF7fxc0ZWLIBGI1TyUVBjgte2fKr6yuanRzBk07jh4aYpVldE4qwNinitgbLByZOKJrg15yq0JmJ03m7S63vhPc7IHUvTll39gGbO7Akn7NOC7TfPG+3peeze8CWcVzpdpKG7bPUWTTnidO8w8H28K4icWL/qVJvk7TaHauTb4LaugPDb06ChjZDgfyvbHzBQIDy5LicZgh1TImhAWLgGEYh5hrqWyCbLT+OZXLLbvnU2/+Vxft+WD2++MNb0eN7iY2Bjf0JhCsp5ulep+cxLc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
